<#
.SYNOPSIS
Moves non-redistributable Unity assets to a private backup and removes generated
Unity files before the public Git repository is initialised.

.DESCRIPTION
Run only after every Unity Editor instance using this project has closed. The
operation is deliberately recoverable for raw assets: each excluded folder is
moved, not deleted, to a path outside the release root. Generated Unity caches
and IDE project files are deleted because Unity recreates them.
#>
[CmdletBinding()]
param(
    [string]$BackupRoot = 'D:\Github\IMPACT\_PRIVATE_DO_NOT_PUBLISH\IMPACT_release_asset_snapshot_20260916'
)

$ErrorActionPreference = 'Stop'
$releaseRoot = Split-Path -Parent $PSScriptRoot
$projectRoot = Join-Path $releaseRoot 'unity_project'
$assetsRoot = Join-Path $projectRoot 'Assets'
$expectedReleaseRoot = 'D:\Github\IMPACT\IMPACT_Public_Release_20260914'

if ((Resolve-Path -LiteralPath $releaseRoot).Path -ne $expectedReleaseRoot) {
    throw "Safety check failed: expected release root '$expectedReleaseRoot', found '$releaseRoot'."
}
if (Get-Process -Name Unity -ErrorAction SilentlyContinue) {
    throw 'Close every Unity Editor process before moving assets. No files were changed.'
}
if (Test-Path -LiteralPath $BackupRoot) {
    throw "Backup target already exists: $BackupRoot. Review it rather than overwriting it."
}

New-Item -ItemType Directory -Path $BackupRoot -Force | Out-Null
$backupAssets = Join-Path $BackupRoot 'Assets'
New-Item -ItemType Directory -Path $backupAssets -Force | Out-Null

# These two first-party extensions were located inside the vendor SDK only for
# the private project. Preserve their GUIDs while moving them into our source.
foreach ($name in @('IMPACTFeedback.cs', 'IMPACTFeedback.cs.meta', 'IMPACTCSV.cs', 'IMPACTCSV.cs.meta')) {
    $source = Join-Path $assetsRoot "Noitom\Scripts\Mocap\$name"
    $destination = Join-Path $assetsRoot "Scripts\$name"
    if (-not (Test-Path -LiteralPath $source)) {
        throw "Expected first-party source is missing: $source"
    }
    if (Test-Path -LiteralPath $destination) {
        throw "Destination already exists: $destination"
    }
    Move-Item -LiteralPath $source -Destination $destination
}

$excludedAssetFolders = @(
    'Avatar',
    'badminton court',
    'Chart And Graph',
    'FRIKI_STUDIO',
    'Noitom',
    'TextMesh Pro'
)

foreach ($folder in $excludedAssetFolders) {
    $source = Join-Path $assetsRoot $folder
    $destination = Join-Path $backupAssets $folder
    if (-not (Test-Path -LiteralPath $source)) {
        throw "Expected asset folder is missing: $source"
    }
    Move-Item -LiteralPath $source -Destination $destination
    $metaSource = "$source.meta"
    if (Test-Path -LiteralPath $metaSource) {
        Move-Item -LiteralPath $metaSource -Destination "$destination.meta"
    }
}

# These are locally generated by Unity/IDE tools and can contain local paths,
# machine metadata, or logs. They are regenerated on the recipient's machine.
foreach ($name in @('.vs', 'Library', 'Logs', 'obj', 'Temp', 'UserSettings')) {
    $target = Join-Path $projectRoot $name
    if (Test-Path -LiteralPath $target) {
        Remove-Item -LiteralPath $target -Recurse -Force
    }
}
Get-ChildItem -LiteralPath $projectRoot -File -Include '*.csproj', '*.sln' |
    Remove-Item -Force

Write-Host 'Public asset boundary completed.'
Write-Host "Private backup: $BackupRoot"
Write-Host 'Next: run tools/check_public_release.ps1, initialise Git, then perform a clean-clone dependency check.'
